language: bash
matrix:
  include:
    - arch: ppc64le # power queue name
      dist: xenial      # power jobs only on ubuntu-xenial distribution
    - os: linux         # Intel queue name
      dist: xenial
   
script:
  - sh bin/test-wget.sh
# - if [ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]; then whoami; fi
# - if [ "$TRAVIS_OS_NAME" == "linux" ]; then whoami; arch; echo $HOSTTYPE $TRAVIS_OS_NAME; perlbrew --version; perlbrew list; fi
